server:
  port: 8181

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:mem:testdb; INIT = RUNSCRIPT FROM 'classpath:schema.sql'
    #url: jdbc:h2:mem:testdb
    #url: jdbc:h2:mem:testdb; INIT = CREATE SCHEMA IF NOT EXISTS testdb\;RUNSCRIPT FROM 'classpath:schema.sql';DB_CLOSE_DELAY=-1'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  main.allow-bean-definition-overriding: true


